server {
    listen 80;

    # Aufruf über Host:8080 => proxied zum Backend im internen Netz
    location / {
        proxy_pass http://backend:5000;
    }

    # Explizites Health-Endpoint fürs Frontend
    location /frontend-health {
        return 200 "frontend ok\n";
        add_header Content-Type text/plain;
    }
}