version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_with_volume
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer_data:/data
